version: '3.6'
services:
  order-service:
    build: order-service
    ports:
      - 9081:9081
      - 9445:9445
    links:
      - inventory-service
      - jaeger-allinone
  inventory-service:
    build: inventory-service
    ports:
      - 9080:9080
      - 9443:9443
  jaeger-allinone:
    image: jaegertracing/all-in-one:1.42
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 4317:4317
      - 4318:4318
      - 9411:9411
      - 14269:14269
      - 16686:16686
      - 14268:14268
networks:
  tracing:
    name: tracing